Repository jacoco/jacoco, pull requests merged in 2020-12, with the labels that each got.

#1130 Use Azure Pipelines instead of Travis
  .azure-pipelines/azure-pipelines.yml
  .azure-pipelines/maven-settings.xml
  .travis.sh
  .travis.yml
  .travis/toolchains.xml
  .travis/travis-toolchains.xml
  .travis/trigger-site-deployment.py
  README.md
  org.jacoco.doc/docroot/doc/environment.html
Labels: component: build

#1131 Print effective Java version in build
  .azure-pipelines/azure-pipelines.yml
Labels: component: build

#1133 Use BeanShell instead of Groovy scripts
  org.jacoco.examples.test/src/test/resources/verify-it.bsh
  org.jacoco.examples.test/src/test/resources/verify-offline.bsh
  org.jacoco.examples.test/src/test/resources/verify.bsh
Labels: component: build

#1132 Add experimental support for Java 17 class files
  .azure-pipelines/azure-pipelines.yml
  org.jacoco.build/pom.xml
  org.jacoco.core.test.validation/pom.xml
  org.jacoco.core.test/src/org/jacoco/core/analysis/AnalyzerTest.java
  org.jacoco.core.test/src/org/jacoco/core/instr/InstrumenterTest.java
  org.jacoco.core/src/org/jacoco/core/internal/instr/InstrSupport.java
  org.jacoco.doc/docroot/doc/changes.html
Labels: component: build, component: core, type: enhancement

#1121 Remove dependency on maven-reporting-impl
  jacoco-maven-plugin/pom.xml
  jacoco-maven-plugin/src/org/jacoco/maven/AbstractReportMojo.java
  jacoco-maven-plugin/src/org/jacoco/maven/FileFilter.java
  jacoco-maven-plugin/src/org/jacoco/maven/ReportAggregateMojo.java
  jacoco-maven-plugin/src/org/jacoco/maven/ReportITMojo.java
  jacoco-maven-plugin/src/org/jacoco/maven/ReportMojo.java
  org.jacoco.doc/docroot/doc/changes.html
Labels: component: maven, type: enhancement
