Repository jacoco/jacoco, pull requests merged in 2023-10, with the labels that each got.

#1515 Fix links to ASM website
  org.jacoco.build/licenses/asm-9.5.html
  org.jacoco.doc/docroot/doc/api.html
  org.jacoco.doc/docroot/doc/flow.html
  org.jacoco.doc/docroot/doc/implementation.html
Labels: component: documentation

#1518 Update ASM to 9.6
  org.jacoco.build/licenses/asm-9.6.html
  org.jacoco.build/pom.xml
  org.jacoco.doc/docroot/doc/changes.html
Labels: component: core

#1519 Fix link to Bytecode Outline Plug-In
  org.jacoco.doc/docroot/doc/flow.html
Labels: component: documentation

#1505 Add validation tests for boolean expressions
  org.jacoco.core.test.validation.java5/src/org/jacoco/core/test/validation/java5/targets/BooleanExpressionsTarget.java
Labels: component: test

#1520 Update documentation: JDK version 21 is officially supported
  org.jacoco.doc/docroot/doc/build.html
  org.jacoco.doc/docroot/doc/changes.html
  org.jacoco.doc/docroot/doc/environment.html
  org.jacoco.doc/docroot/doc/faq.html
Labels: component: documentation

#1492 Restore exec file compatibility after upgrade of ASM to version 9.5
  org.jacoco.core.test/src/org/jacoco/core/internal/analysis/MethodAnalyzerTest.java
  org.jacoco.core.test/src/org/jacoco/core/internal/flow/LabelFlowAnalyzerTest.java
  org.jacoco.core.test/src/org/jacoco/core/internal/instr/ZeroLineNumberTest.java
  org.jacoco.core/src/org/jacoco/core/internal/flow/LabelFlowAnalyzer.java
  org.jacoco.doc/docroot/doc/changes.html
Labels: type: bug :bug:, component: core

#1529 Use SPDX identifier for license declaration in pom.xml
  org.jacoco.build/pom.xml
Labels: component: build
