Repository jacoco/jacoco, pull requests merged in 2024-11, with the labels that each got.

#1776 Fix warning "'reportOutputDirectory' is unknown for plugin 'maven-javadoc-plugin:3.11.1:jar (attach-javadocs)'"
  org.jacoco.doc/pom.xml
Labels: component: build

#1774 KotlinWhenFilter should handle nullable enums
  org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinWhenExpressionTarget.kt
  org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinWhenFilterTest.java
  org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinWhenFilter.java
  org.jacoco.doc/docroot/doc/changes.html
Labels: component: core.filters, language: Kotlin

#1777 Fix typo
  org.jacoco.core/src/org/jacoco/core/internal/flow/LabelInfo.java
Labels: component: documentation

#1778 Split KotlinWhenExpressionTarget
  org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/KotlinWhenEnumTest.java
  org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/KotlinWhenSealedTest.java
  org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/KotlinWhenStringTest.java
  org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinWhenEnumTarget.kt
  org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinWhenSealedTarget.kt
  org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinWhenStringTarget.kt
Labels: component: test, language: Kotlin

#1770 Validation tests should create ASMified and TEXTified bytecode representations
  org.jacoco.core.test/src/org/jacoco/core/test/validation/ValidationTestBase.java
Labels: component: test

#1781 Fix typo: replace "a instrumented" by "an instrumented"
  org.jacoco.core.test/src/org/jacoco/core/test/perf/ExecuteInstrumentedCodeScenario.java
  org.jacoco.core/src/org/jacoco/core/instr/Instrumenter.java
  org.jacoco.core/src/org/jacoco/core/internal/instr/ClassInstrumenter.java
Labels: component: documentation

#1782 Fix typo: replace "an child" by "a child"
  org.jacoco.report/src/org/jacoco/report/internal/xml/XMLElement.java
Labels: component: documentation

#1783 Fix typo
  org.jacoco.report/src/org/jacoco/report/internal/html/page/SessionsPage.java
Labels: component: documentation

#1784 Build should not produce warning about generation of JUnit report
  org.jacoco.doc/pom.xml
Labels: component: build

#1780 Do not test with SecurityManager when Java version 24 and above
  org.jacoco.ant.test/pom.xml
  org.jacoco.ant.test/src/org/jacoco/ant/CoverageTaskTest.xml
  org.jacoco.ant.test/src/org/jacoco/ant/InstrumentTaskTest.xml
  org.jacoco.ant.test/src/org/jacoco/ant/SecurityManagerTest.java
  org.jacoco.ant.test/src/org/jacoco/ant/SecurityManagerTest.xml
  org.jacoco.ant.test/src/org/jacoco/ant/empty.xml
Labels: component: test, type: lifecycle :recycle:

#1785 SecurityManagerTest should not depend on CoverageTaskTest
  org.jacoco.ant.test/src/org/jacoco/ant/SecurityManagerTest.xml
Labels: component: test

#1786 Fix typo: replace "a instance" by "an instance"
  org.jacoco.core/src/org/jacoco/core/data/ExecutionDataStore.java
  org.jacoco.core/src/org/jacoco/core/internal/analysis/MethodCoverageCalculator.java
  org.jacoco.report/src/org/jacoco/report/internal/xml/XMLElement.java
Labels: component: documentation

#1789 Fix typo: replace "an listener" by "a listener"
  org.jacoco.core/src/org/jacoco/core/data/ExecutionDataReader.java
  org.jacoco.core/src/org/jacoco/core/runtime/RemoteControlReader.java
Labels: component: documentation

#1788 Fix javadoc doclint warning "no @param for fragment"
  org.jacoco.core/src/org/jacoco/core/internal/analysis/SourceNodeImpl.java
Labels: component: documentation

#1791 Add validation test for Kotlin `when` statement with `sealed class` subject type
  org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinWhenSealedTarget.kt
Labels: component: core.filters, component: test, language: Kotlin

#1790 Fix typo: replace "a XML" by "an XML"
  org.jacoco.doc/docroot/doc/ant.html
  org.jacoco.report/src/org/jacoco/report/internal/xml/ReportElement.java
  org.jacoco.report/src/org/jacoco/report/internal/xml/XMLElement.java
Labels: component: documentation

#1792 Add unit test for LocalProbeArrayStrategy
  org.jacoco.core.test/src/org/jacoco/core/internal/instr/LocalProbeArrayStrategyTest.java
Labels: component: test

#1793 Fix typo: replace "a HTML" by "an HTML"
  org.jacoco.examples/src/org/jacoco/examples/ReportGenerator.java
  org.jacoco.report/src/org/jacoco/report/internal/html/IHTMLReportContext.java
  org.jacoco.report/src/org/jacoco/report/internal/html/index/ElementIndex.java
Labels: component: documentation

#1795 Fix typo: replace "a agent" by "an agent"
  org.jacoco.agent.rt/src/org/jacoco/agent/rt/internal/Agent.java
  org.jacoco.core/src/org/jacoco/core/runtime/AgentOptions.java
Labels: component: documentation

#1796 Add unit test for ClassFieldProbeArrayStrategy
  org.jacoco.core.test/src/org/jacoco/core/internal/instr/ClassFieldProbeArrayStrategyTest.java
Labels: component: test

#1798 Fix javadoc doclint warnings "no comment"
  org.jacoco.core/src/org/jacoco/core/analysis/CounterComparator.java
  org.jacoco.core/src/org/jacoco/core/analysis/NodeComparator.java
  org.jacoco.core/src/org/jacoco/core/data/IncompatibleExecDataVersionException.java
  org.jacoco.core/src/org/jacoco/core/internal/analysis/ClassCoverageImpl.java
  org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinGeneratedFilter.java
  org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinSMAP.java
Labels: component: documentation

#1457 Upgrade maven-invoker-plugin to 3.8.1
  .github/dependabot.yml
  jacoco-maven-plugin.test/pom.xml
  org.jacoco.build/pom.xml
  org.jacoco.examples.test/pom.xml
Labels: component: build

#1799 Fix typos
  org.jacoco.core.test.validation.java5/src/org/jacoco/core/test/validation/java5/EnumSwitchTest.java
  org.jacoco.core.test.validation.java5/src/org/jacoco/core/test/validation/java5/ExplicitInitialFrameTest.java
  org.jacoco.core.test.validation.java5/src/org/jacoco/core/test/validation/java5/ImplicitFieldInitializationTest.java
  org.jacoco.core.test.validation.java5/src/org/jacoco/core/test/validation/java5/targets/EnumSwitchTarget.java
  org.jacoco.core.test.validation.java5/src/org/jacoco/core/test/validation/java5/targets/ExceptionsTarget.java
  org.jacoco.core.test/src/org/jacoco/core/test/perf/IPerfOutput.java
  org.jacoco.core.test/src/org/jacoco/core/test/validation/targets/Stubs.java
  org.jacoco.core/src/org/jacoco/core/data/ExecutionDataWriter.java
  org.jacoco.core/src/org/jacoco/core/data/SessionInfo.java
  org.jacoco.core/src/org/jacoco/core/data/SessionInfoStore.java
  org.jacoco.core/src/org/jacoco/core/internal/analysis/SourceNodeImpl.java
  org.jacoco.core/src/org/jacoco/core/internal/flow/LabelInfo.java
  org.jacoco.core/src/org/jacoco/core/internal/instr/InstrSupport.java
  org.jacoco.core/src/org/jacoco/core/internal/instr/SignatureRemover.java
  org.jacoco.core/src/org/jacoco/core/runtime/IRemoteCommandVisitor.java
  org.jacoco.core/src/org/jacoco/core/runtime/RuntimeData.java
  org.jacoco.examples/src/org/jacoco/examples/ClassInfo.java
  org.jacoco.examples/src/org/jacoco/examples/CoreTutorial.java
  org.jacoco.examples/src/org/jacoco/examples/ExecDump.java
  org.jacoco.report/src/org/jacoco/report/internal/html/table/ITableItem.java
  org.jacoco.report/src/org/jacoco/report/internal/html/table/SortIndex.java
Labels: component: documentation

#1797 Add convenience method for asserting MethodNodes
  org.jacoco.core.test/src/org/jacoco/core/instr/MethodRecorder.java
  org.jacoco.core.test/src/org/jacoco/core/internal/flow/MethodSanitizerTest.java
  org.jacoco.core.test/src/org/jacoco/core/internal/instr/ClassFieldProbeArrayStrategyTest.java
Labels: component: test
